python run_lm_finetuning.py \
            --output_dir=gpt_cose_multi_task \
            --model_type=openai-gpt \
            --model_name_or_path=openai-gpt \
            --do_train \
            --evaluate_during_training \
            --train_data_file=$1 \
            --do_eval \
            --eval_data_file=$2 \
            --per_gpu_train_batch_size=2 \
            --gradient_accumulation_steps=4 \
            --per_gpu_eval_batch_size=1 \
            --warmup_steps=600 \
            --num_train_epochs=4 \
            --block_size=128 \
	    --do_lower_case \
            --overwrite_cache
